app:
  name: "crypto_data_pipeline"
  log_level: "INFO"

api:
  base_url: "https://api.coingecko.com/api/v3"
  endpoint: "/coins/markets"
  vs_currency: "usd"
  per_page: 100
  page: 1

postgres:
  host: "localhost"
  port: 5432
  dbname: "crypto_pipeline_db"
  user: "Your_user"
  password: "your_pasword"
  schema: "crypto"